name: "kreastol-legacy-community"

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: Kreastol
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "1041:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - klc
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - "1042:80"
    networks:
      - klc
  website:
    image: local-image:latest
    container_name: website
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1043:80"
    networks:
      - klc
    environment:
      - DB_HOST=db
      - DB_USER=db_user
      - DB_PASS=db_user_pass
      # SMTP, Make sure to change the following values
      # Get your SMTP credentials from your email provider
      # Outlook: https://account.live.com/proofs/AppPassword
      # Gmail: https://myaccount.google.com/apppasswords
      - SMTP_SENDER=<email>
      - SMTP_PASS=<password>
      - SMTP_HOST=<smtp_host>
volumes:
  dbdata:

networks:
  klc:
    ipam:
      config:
        - subnet: 172.20.0.0/16
